# Generated by Django 2.1 on 2018-09-25 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('state', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=12)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mistakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_type', models.CharField(max_length=45)),
                ('mistake_title', models.CharField(max_length=45)),
                ('comment', models.TextField()),
                ('state', models.CharField(choices=[('Not Solved', 'Not Solved'), ('In Progress', 'In Progress'), ('Reviewed', 'Reviewed')], default='Not Solved', max_length=12)),
                ('qualification', models.IntegerField()),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.homework')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('project_date', models.DateField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.client')),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('scrum_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.project')),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Scrum Master', 'Scrum Master'), ('Product Owner', 'Product Owner'), ('Team', 'Team')], default='Team', max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='requirement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.requirement'),
        ),
        migrations.AddField(
            model_name='homework',
            name='user_id_in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homework',
            name='user_id_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='homework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.homework'),
        ),
    ]
